# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'COVID-19Board' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for COVID-19Board

  pod 'Alamofire', '~> 5.5' 
  pod 'ChartsRealm'
  pod 'Charts'

  target 'COVID-19BoardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'COVID-19BoardUITests' do
    # Pods for testing
  end

end
